# Generated by Django 6.0.1 on 2026-03-17 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.CharField(default='CSC-25S-606', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
