# Generated by Django 6.0.1 on 2026-03-17 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_datesheetentry_course_by_section'),
        ('accounts', '0002_student_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='academics.department'),
            preserve_default=False,
        ),
    ]
