# Generated by Django 6.0.1 on 2026-03-19 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='transaction_type',
            field=models.CharField(choices=[('charge', 'Charge (Enrollment)'), ('payment', 'Payment (Stripe)'), ('refund', 'Refund (Drop)'), ('service', 'Service/Other Charge'), ('fine', 'Late Fine/Penalty')], max_length=20),
        ),
    ]
