# Generated by Django 6.0.1 on 2026-03-09 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_enrollment_unique_together_and_more'),
        ('accounts', '0002_student_cached_balance'),
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_types', models.CharField(choices=[('charge', 'Charge (Enrollment)'), ('payment', 'Payment (Stripe)'), ('refund', 'Refund (Drop)')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.enrollment')),
                ('payment_reference', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.payment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='accounts.student')),
            ],
        ),
    ]
