# Generated by Django 6.0.1 on 2026-03-09 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_ledger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ledger',
            old_name='transaction_types',
            new_name='transaction_type',
        ),
    ]
