# Generated by Django 6.0.1 on 2026-03-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('credit_hours', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_code', models.CharField(max_length=10, unique=True)),
                ('course_type', models.CharField(choices=[('Lab', 'Lab'), ('Theory', 'Theory')], default='Theory', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseBySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code_by_section', models.PositiveSmallIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('no_of_enrolled_students', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('building', models.CharField(choices=[('Talpur House', 'Talpur House'), ('Main Building', 'Main Building'), ('IT Tower', 'IT Tower')], default='Main Building', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Assignment', 'Assignment'), ('Participation', 'Participation'), ('Presestation', 'Presentation'), ('Project', 'Project'), ('Midterm', 'Midterm'), ('Finalterm', 'Finalterm'), ('LabExam', 'LabExam'), ('LabAtt', 'LabAtt'), ('LabViva', 'LabViva'), ('LabManual', 'LabManual')], max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('obtained_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.CharField(max_length=25, unique=True)),
                ('limit_of_students', models.PositiveSmallIntegerField(default=50)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(choices=[('Fall', 'Fall'), ('Spring', 'Spring')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('add_course_deadline', models.DateField(blank=True, null=True)),
                ('drop_course_deadline', models.DateField(blank=True, null=True)),
                ('fee_payment_deadline', models.DateField(blank=True, null=True)),
                ('voucher_validity_days', models.PositiveSmallIntegerField(default=7)),
                ('max_credit_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
    ]
