# Generated by Django 6.0.1 on 2026-03-16 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceentry',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_sessions', to='accounts.instructor'),
        ),
        migrations.AddField(
            model_name='classsession',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='academics.classschedule'),
        ),
        migrations.AddField(
            model_name='attendanceentry',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.classsession'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.instructor'),
        ),
        migrations.AddField(
            model_name='coursebysection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.course'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course_by_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.coursebysection'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='course_by_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.coursebysection'),
        ),
        migrations.AddField(
            model_name='datesheetentry',
            name='course_by_section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academics.coursebysection'),
        ),
        migrations.AddField(
            model_name='department',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='academics.building'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_by_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.coursebysection'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='markentry',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='room',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='academics.department'),
        ),
        migrations.AddField(
            model_name='datesheetentry',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_dates', to='academics.room'),
        ),
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.department'),
        ),
        migrations.AddField(
            model_name='coursebysection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.section'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='classschedule',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='attendanceentry',
            unique_together={('session', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together={('enrollment', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='coursebysection',
            unique_together={('course', 'section')},
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'course_by_section', 'semester'), name='unique_active_enrollment'),
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course_by_section', 'instructor', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='classschedule',
            unique_together={('course_by_section', 'semester', 'day_of_the_week')},
        ),
    ]
