# Generated by Django 6.0.1 on 2026-03-02 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseassignment',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.instructor'),
        ),
        migrations.AddField(
            model_name='coursebysection',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.course'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='course_by_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.coursebysection'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='course_by_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.coursebysection'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='accounts.student'),
        ),
        migrations.AddField(
            model_name='markentry',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.enrollment'),
        ),
        migrations.AddField(
            model_name='section',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.department'),
        ),
        migrations.AddField(
            model_name='coursebysection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.section'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.semester'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.semester'),
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together={('enrollment', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='coursebysection',
            unique_together={('course', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'course_by_section', 'semester')},
        ),
        migrations.AlterUniqueTogether(
            name='courseassignment',
            unique_together={('course_by_section', 'instructor', 'semester')},
        ),
    ]
