# Generated by Django 6.0.1 on 2026-03-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dropped', 'Dropped (Before Deadline)'), ('withdrawn', 'Withdrawn (After Deadline)')], default='active', max_length=30),
        ),
    ]
