# Generated by Django 6.0.1 on 2026-03-16 20:01

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datesheetentry',
            name='exam_type',
            field=models.CharField(choices=[('Midterm', 'Midterm Examination'), ('Finalterm', 'Final Examination')], default=datetime.datetime(2026, 3, 16, 20, 1, 30, 802256, tzinfo=datetime.timezone.utc), max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datesheetentry',
            name='course_by_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.coursebysection'),
        ),
        migrations.AlterUniqueTogether(
            name='datesheetentry',
            unique_together={('course_by_section', 'exam_type')},
        ),
    ]
