# Generated by Django 6.0.1 on 2026-03-05 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_enrollment_fee_amount_enrollment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='exam_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
