# Generated by Django 6.0.1 on 2026-03-16 20:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_datesheetentry_exam_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datesheetentry',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datesheet_entries', to='academics.semester'),
            preserve_default=False,
        ),
    ]
