# Generated by Django 6.0.1 on 2026-03-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_enrollment_exam_fee'),
        ('accounts', '0002_student_cached_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'course_by_section', 'semester'), name='unique_active_enrollment'),
        ),
    ]
