# Generated by Django 6.0.1 on 2026-03-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_datesheetentry_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='is_admit_card_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semester',
            name='is_datesheet_published',
            field=models.BooleanField(default=False),
        ),
    ]
