# Generated by Django 6.0.1 on 2026-03-17 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_semester_is_admit_card_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datesheetentry',
            name='course_by_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datesheet_entries', to='academics.coursebysection'),
        ),
    ]
