# Generated by Django 6.0.1 on 2026-03-17 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_datesheetentry_course_by_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='classschedule',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='academics.room'),
            preserve_default=False,
        ),
    ]
