# Generated by Django 6.0.1 on 2026-03-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_classschedule_classsession_attendanceentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='markentry',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='markentry',
            name='category',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Participation', 'Participation'), ('Presentation', 'Presentation'), ('Project', 'Project'), ('Midterm', 'Midterm'), ('Finalterm', 'Finalterm'), ('LabExam', 'LabExam'), ('LabAtt', 'LabAtt'), ('LabViva', 'LabViva'), ('LabManual', 'LabManual')], max_length=20),
        ),
    ]
