# Generated by Django 6.0.1 on 2026-03-15 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_markentry_is_locked_alter_markentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markentry',
            name='category',
            field=models.CharField(choices=[('Assignment', 'Assignment'), ('Participation', 'Participation'), ('Presestation', 'Presentation'), ('Project', 'Project'), ('Midterm', 'Midterm'), ('Finalterm', 'Finalterm'), ('LabExam', 'LabExam'), ('LabAtt', 'LabAtt'), ('LabViva', 'LabViva'), ('LabManual', 'LabManual')], max_length=20),
        ),
    ]
