# Generated by Django 6.0.1 on 2026-03-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_classschedule_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('PROG', 'Programming'), ('MATH', 'Mathematics'), ('THEO', 'Theory'), ('SOFT', 'Software Engineering'), ('GEN', 'General Education')], default='GEN', max_length=20),
        ),
    ]
