# Generated by Django 6.0.1 on 2026-06-21 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_courseassignment_result_uploaded'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('course_type', models.CharField(choices=[('Theory', 'Theory'), ('Lab', 'Lab')], default='Theory', max_length=30)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='markentry',
            unique_together=set(),
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('total_marks', models.PositiveBigIntegerField()),
                ('course_by_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.coursebysection')),
            ],
        ),
        migrations.AddField(
            model_name='markentry',
            name='assessment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mark_entries', to='academics.assessment'),
        ),
        migrations.AddConstraint(
            model_name='markentry',
            constraint=models.UniqueConstraint(fields=('enrollment', 'assessment'), name='unique_mark_per_assessment'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.assessmenttype'),
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='title',
        ),
        migrations.RemoveField(
            model_name='markentry',
            name='total_marks',
        ),
    ]
