# Generated by Django 6.0.1 on 2026-06-21 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_assessmenttype_alter_markentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markentry',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mark_entries', to='academics.assessment'),
        ),
    ]
