# Generated by Django 6.0.1 on 2026-06-22 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_alter_markentry_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebysection',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='course_by_section', to='academics.semester'),
            preserve_default=False,
        ),
    ]
