# Generated by Django 6.0.1 on 2026-06-23 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_coursebysection_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebysection',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courby_section', to='academics.semester'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('course_by_section', 'title'), name='unique_title_per_assessment'),
        ),
    ]
