# Generated by Django 6.0.1 on 2026-06-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_alter_coursebysection_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='is_requried',
            field=models.BooleanField(default=False),
        ),
    ]
