# Generated by Django 6.0.1 on 2026-06-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_assessmenttype_is_requried'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmenttype',
            name='is_unique',
            field=models.BooleanField(default=False),
        ),
    ]
