# Generated by Django 6.0.1 on 2026-06-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_assessmenttype_is_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='grading_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
