# Generated by Django 6.0.1 on 2026-06-26 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_semester_grading_deadline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markentry',
            name='is_locked',
        ),
    ]
