# Generated by Django 6.0.1 on 2026-02-17 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('per_credit', 'Price of Credit Hour'), ('lab_fee', 'Fixed Lab Fee'), ('registration', 'Semester Registration'), ('exam_fee', 'Examination Fee'), ('library_fee', 'Library Charges')], max_length=30, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='voucheritem',
            name='course_by_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_items', to='app1.coursebysection'),
        ),
    ]
