# Generated by Django 6.0.1 on 2026-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_feeconfiguration_alter_voucheritem_course_by_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='fee_payment_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='semester',
            name='voucher_validity_days',
            field=models.PositiveSmallIntegerField(default=7),
        ),
        migrations.AlterField(
            model_name='feeconfiguration',
            name='name',
            field=models.CharField(choices=[('per_credit', 'Price of Credit Hour'), ('registration', 'Semester Registration'), ('exam_fee', 'Examination Fee'), ('library_fee', 'Library Charges')], max_length=30, unique=True),
        ),
    ]
